language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-27.0.3
    - platform-tools
    - tools
    - android-27
    - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
before_install: yes | sdkmanager "platforms;android-27"
script: ./gradlew assemble lint
